### ISSUE TITLE
Add working with `serviceUrl`/`returnUrl` and examples.

### ISSUE THREAD

**Issue by Spell6inder** [wayforpay/php-sdk#1]
It would be nice to add support for handling requests from WayForPay on `serviceUrl`/`returnUrl` and generating a response. Also add examples of these actions.

**Comment by vlydev** [comment]
Hi. Fine. I will do it in 1-2 days.

**Comment by vlydev** [comment]
Hi everyone. Please try next:
https://github.com/wayforpay/php-sdk#service-url
https://github.com/wayforpay/php-sdk#return-url

**Comment by Spell6inder** [comment]
Thanks!
